# Generated by Django 4.1.3 on 2022-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_alter_favorite_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('add_date',)},
        ),
        migrations.AddField(
            model_name='favorite',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
