# Generated by Django 4.1.3 on 2022-12-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_alter_favorite_options_favorite_add_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-add_date',)},
        ),
    ]
