# Generated by Django 4.1.3 on 2022-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-create_date',)},
        ),
        migrations.AddField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
