# Generated by Django 4.1.3 on 2022-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_cart_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
